Add retry func
maiha/yahoojp-ads-downloader pull request #5
Opened 2023-01-25 08:09 UTC by norihito-sato-ss

2023-01-26 03:40 UTC, maiha requested changes

2023-01-26 03:40 UTC, maiha commented on lib/service.mk
> +	@for i in `seq ${RETRY_COUNT}`; do\
curlにはretry系のオプションがあるので、loopではなく、そちらを使う方がコードがシンプルになりそうです。

2023-01-26 03:40 UTC, maiha commented on lib/service.mk
> +	@grep -q '"errors":null' "$3.err" || jq .errors "$3.err" || exit 1
ここの `exit` は不要です。
「連続してAPI実行を行いたい」（失敗しても次へ）という処理が表現できなくなるためです。

2023-01-26 06:19 UTC, norihito-sato-ss commented on lib/service.mk
> +	@for i in `seq ${RETRY_COUNT}`; do\
ありがとうございます。🙇
curlにretry系のオプションあるんですね。

2023-01-26 06:20 UTC, norihito-sato-ss commented on lib/service.mk
> +	@grep -q '"errors":null' "$3.err" || jq .errors "$3.err" || exit 1
ありがとうございます。🙇
承知しました。

2023-02-06 01:52 UTC, maiha approved these changes
良きです！お疲れ様でした 👍

2023-02-06 02:28 UTC, norihito-sato-ss commented
ご確認ありがとうございます。🙇

2023-02-17 06:16 UTC, norihito-sato-ss commented
以下にまとめてあるため、こちらはクローズします。
https://github.com/maiha/yahoojp-ads-downloader/pull/6

2023-02-17 06:16 UTC, closed without merging