display/search: API v11->v12
maiha/yahoojp-ads-downloader pull request #9
Opened 2024-05-22 01:09 UTC by norihito-sato-ss

2024-05-22 02:42 UTC, maiha requested changes

2024-05-22 02:42 UTC, maiha commented on search/BaseAccountService/Makefile
> +          "${ENDPOINT}/${SERVICE}/get" > res.json
ターゲットファイル名で、直接書き出してしまうと、curlがエラーだった場合、
* 正しくない `res.json` が作られてしまう
* 再実行時は、ファイルがあるためコードが実行されない (リカバーできない)

となりそうです。(Makefileの使いづらい仕様)

また、ここで作成したファイルはこの後のAPI実行で利用され続けるため、一時的な `res.json` という名前でなく、 `base_account_id.json` のようなファイル名で永続化しておく方が、利用する時のコードで可読性が高まりそうです。

このへんは、通常のAPI実行よりも、oauthトークン取得の方のコードが参考になると思います。
→ `oauth/Makefile` の `token.json:`

* curlエラー時のりカバー
* 取得したjsonが意味的に正しいかチェック (以降のAPI実行で空のbase_idが利用されたりしないように)

あたりを意識して、ちょっと修正してみて下さい 🙇

2024-05-22 02:53 UTC, norihito-sato-ss commented on search/BaseAccountService/Makefile
> +          "${ENDPOINT}/${SERVICE}/get" > res.json
ありがとうございます。🙇

2024-05-27 02:23 UTC, maiha requested changes
grepよりjqで厳密にチェックした方が良い気がしてきました。
申し訳ないですが、再度対応お願いします 🙇

2024-05-27 02:23 UTC, maiha commented on lib/service.mk
> +	@rm -f $(BASE_ACCOUNT_JSON)
ここは消さずに残しておくほうがよさそうです
* base_account_id の値は同じ (少なくとも1回のfeeder実行中は)
* base_account_id の取得はコストがかかる
* 何百回も実行されるAPIの度に base_account_id を再取得するのはもったいない

2024-05-27 02:23 UTC, maiha commented on display/BaseAccountService/Makefile
> +	@grep accountId "$(BASE_ACCOUNT_JSON).tmp" > /dev/null
取得したJSONのデータ検証ありがとうございます。
自分はtokenを雑にgrepで済ませておいて恐縮ですが、ここのレスポンスは構造が複雑なので、もう少し厳密にチェックしたいかもです。

```console
jq --exit-status '.rval.values[0].account.accountId'
```

* 取得時と同じjqで検査する
* 値がない場合に null で正常終了されるのは困るので `--exit-status` する

よく考えたら、ここまで厳密に検査したなら、その出力を `base_account_id.txt` とかに入れておいて、API実行時は cat する方がスマートかもしれない。

2024-05-27 02:23 UTC, maiha commented on search/BaseAccountService/Makefile
> +	@grep accountId "$(BASE_ACCOUNT_JSON).tmp" > /dev/null
ここも同様にgrep→「jqの検査」で 🙏

2024-05-27 02:32 UTC, norihito-sato-ss commented on lib/service.mk
> +	@rm -f $(BASE_ACCOUNT_JSON)
ありがとうございます。 🙇
承知しました。

2024-05-27 02:33 UTC, norihito-sato-ss commented on display/BaseAccountService/Makefile
> +	@grep accountId "$(BASE_ACCOUNT_JSON).tmp" > /dev/null
ありがとうございます。 🙇
承知しました。

2024-05-27 02:33 UTC, norihito-sato-ss commented on search/BaseAccountService/Makefile
> +	@grep accountId "$(BASE_ACCOUNT_JSON).tmp" > /dev/null
ありがとうございます。 🙇
承知しました。

2024-05-30 23:26 UTC, maiha requested changes
以下のようにするとスッキリすると気づきました。
重ねての修正になって申し訳ないですが、対応お願いします 🙇 

(利用側)
make -C (相手) base_account_id.txt

(提供側)
base_account_id.txt: ...

2024-05-30 23:26 UTC, maiha commented on lib/service.mk
> +	@if [ ! -e $(BASE_ACCOUNT_ID_TEXT) ]; then \
ここは、Makefileの冪等性を最大限に利用して、 `make -c "相手"` するだけの方が良い気がしてきました。

(pros)
* base_account_id_text が既に存在するかどうか、などの「作成条件」は相手側に委ねる
* 利用者側は相手側に「作って」だけ依頼する形式にでき、シンプルで可読性も高い
* 今後の新しい条件発生時に、利用箇所を全部修正して周るより、提供側の１箇所の修正で済んで楽できる

(cons)
* 利用側と提供側を疎結合という目的と、run実行後の成果物のファイル名が `base_account_id.txt` だと利用側が内部情報を強く知っている事、は矛盾してないか？

(結論)
* 利用側は `make 欲しいファイル名` にする
* 提供側はその「ファイル名」を作る (条件や冪等性も全部担保する)

```Makefile
@make -s -C ../BaseAccountService "$(notdir $(BASE_ACCOUNT_ID_TEXT))"
```

で、提供側の `BaseAccountService` に `base_account_id.txt` というタスクを追加する。

2024-05-30 23:26 UTC, maiha commented on lib/service.mk
> +	@rm -f $(BASE_ACCOUNT_JSON)
ここまだ消えてなかった

2024-05-30 23:26 UTC, maiha commented on search/BaseAccountService/Makefile
> +	$(MAKE) recv
抽象的なrecvをやめて、「提供するファイル名」をターゲット名に変更
```suggestion
	$(MAKE) "$(BASE_ACCOUNT_ID_TEXT)"
```

run 自体は、実行の「抽象的なエントリーポイント名」として残す

2024-05-30 23:26 UTC, maiha commented on search/BaseAccountService/Makefile
> +recv: req.json
`recv` → `$(BASE_ACCOUNT_ID_TEXT)` に変更

2024-05-30 23:26 UTC, maiha commented on search/BaseAccountService/Makefile
> +	  -d "@req.json" > "$(BASE_ACCOUNT_JSON).tmp"
ここは以下の理由で tmp は不要になっちゃいました
* base_account_json 自体は外部に提供する情報ではなくなった
* base_account_json が最終成果物のファイル名でなくなったため、中途半端に存在していても冪等性を妨げない 

依頼した修正のrevertになって申し訳ないです

2024-05-30 23:26 UTC, maiha commented on search/BaseAccountService/Makefile
> +	@jq --exit-status '.rval.values[0].account.accountId' $(BASE_ACCOUNT_JSON) > $(BASE_ACCOUNT_ID_TEXT)
逆にこちらの BASE_ACCOUNT_ID_TEXT が最終成果物になるので、tmp化が必要になります。
また、ターゲットファイル名は `$@` で簡易表記できるので、それを使うとシンプルになります。
```suggestion
	@jq --exit-status '.rval.values[0].account.accountId' $(BASE_ACCOUNT_JSON) > "$@.tmp"				
	@mv "$@.tmp" "$@"
```

2024-05-31 01:57 UTC, norihito-sato-ss commented on lib/service.mk
> +	@if [ ! -e $(BASE_ACCOUNT_ID_TEXT) ]; then \
ありがとうございます。🙇
修正します。

2024-05-31 01:57 UTC, norihito-sato-ss commented on search/BaseAccountService/Makefile
> +recv: req.json
ありがとうございます。🙇
修正します。

2024-05-31 01:57 UTC, norihito-sato-ss commented on search/BaseAccountService/Makefile
> +	@jq --exit-status '.rval.values[0].account.accountId' $(BASE_ACCOUNT_JSON) > $(BASE_ACCOUNT_ID_TEXT)
ありがとうございます。🙇
修正します。

2024-05-31 01:58 UTC, norihito-sato-ss commented on search/BaseAccountService/Makefile
> +	  -d "@req.json" > "$(BASE_ACCOUNT_JSON).tmp"
承知しました。🙇

2024-05-31 01:58 UTC, norihito-sato-ss commented on search/BaseAccountService/Makefile
> +	$(MAKE) recv
ありがとうございます。🙇
修正します。

2024-05-31 01:58 UTC, norihito-sato-ss commented on lib/service.mk
> +	@rm -f $(BASE_ACCOUNT_JSON)
忘れてました。🙇
修正します。

2024-05-31 05:06 UTC, maiha requested changes

2024-05-31 05:06 UTC, maiha commented on display/BaseAccountService/Makefile
> +	@if [ ! -e $(BASE_ACCOUNT_ID_TEXT) ]; then \
ここのif文は省略できます。

というか多分、Makefileのルールの説明をしたことなかったかもです。失礼しました。

先にシェルスクリプトの場合を例にすると、こういう冪等性を実現するには、書いてもらった通りのif文が必要になります。

```bash
if (対象ファイルがない) # 初回用
  if (作成に使ったsrcファイルが、対象ファイルより新しい) # 冪等かつsrc更新時の対応
    (メインの処理)
  fi
fi
```

* 「冪等性の担保」のための税金みたいなif文がボイラーテンプレートすぎて無駄
* しかもあちこちに出現してきて、依存関係も入るとifがどんどん多重化して可読性が悪い
* できれば、本来の「メインの処理」だけ簡潔に書きたい

というニーズを満たすために、Makefileが生まれました (多分)

```Makefile
(ターゲット): (src)
  (メインの処理)
```

こういうファイル生成ルールを書くだけで、makeでは全部いい感じに冪等性を担保してくれます。
したがって、メイン処理の部分にif文は不要になります。

2024-06-03 00:55 UTC, norihito-sato-ss commented on display/BaseAccountService/Makefile
> +	@if [ ! -e $(BASE_ACCOUNT_ID_TEXT) ]; then \
そうだったんですね。
ありがとうございます。 🙇
修正します。

2024-06-03 02:04 UTC, maiha approved these changes
ありがとうございます！

2024-06-03 02:05 UTC, merged